import Head from 'next/head'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Sass Starter</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next Sass Starter</h1>
      </main>

      <footer className={styles.footer}>
        <p>empty footer</p>
      </footer>
    </div>
  )
}
